#!/bin/sh
# 不要なプロセスを終了させる
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# XFCEセッションを開始する
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
startxfce4 &